#!/usr/bin/env python3
"""Generate docs/api.md from src/avm_cbor.erl.

Dependency-free public API documentation generator.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src" / "avm_cbor.erl"
OUT = ROOT / "docs" / "api.md"

DESCRIPTIONS = {
    "decode/1": ("Decode one CBOR item using default options.", "Reads one complete CBOR value and returns the decoded value plus trailing bytes.", "It is not a strict whole-binary decoder; use decode_all/1 for that."),
    "decode/2": ("Decode one CBOR item using explicit options.", "Applies caller-provided limits and feature flags while decoding one item.", "It does not silently ignore invalid options."),
    "decode_all/1": ("Decode a complete CBOR sequence using default options.", "Consumes all CBOR items and succeeds only when no trailing data remains.", "It is not meant for incomplete stream buffers; use decode_sequence/1 for that."),
    "decode_all/2": ("Decode a complete CBOR sequence using explicit options.", "Consumes all CBOR items while applying caller-provided limits and feature flags.", "It does not accept malformed or incomplete trailing data."),
    "decode_sequence/1": ("Decode as many complete CBOR items as possible using default options.", "Returns complete items and keeps a truncated final item as Rest.", "It is not a whole-input validation helper; use decode_all/1 for that."),
    "decode_sequence/2": ("Decode as many complete CBOR items as possible using explicit options.", "Like decode_sequence/1, but applies caller-provided limits and feature flags.", "It does not hide malformed data; malformed items still return errors."),
    "encode/1": ("Encode one supported Erlang value using default options.", "Produces a definite-length CBOR binary for the supported public value representation.", "It does not produce canonical CBOR or half-precision float output."),
    "encode/2": ("Encode one supported Erlang value using explicit options.", "Applies caller-provided limits and feature flags while encoding.", "It does not support arbitrary Erlang terms outside the documented representation."),
    "get/2": ("Look up a key in a decoded CBOR map.", "Searches the {map, Pairs} representation and returns {ok, Value} when present.", "It is not an Erlang map helper; decoded CBOR maps are represented as pair lists."),
    "get/3": ("Look up a key in a decoded CBOR map with a default.", "Returns the value when present, otherwise returns the supplied default.", "It does not distinguish a missing key from a present value equal to the default."),
    "require/2": ("Require a key in a decoded CBOR map.", "Returns a structured missing-key error when the key is absent.", "It does not validate the value type; use as_text/1, as_int/1, or related helpers."),
    "as_text/1": ("Extract a decoded CBOR text string.", "Accepts {text, Bin} and returns the UTF-8 binary.", "It does not accept arbitrary binaries; use as_bytes/1 for byte strings."),
    "as_bytes/1": ("Extract a decoded CBOR byte string.", "Accepts a binary byte string and returns it unchanged.", "It does not accept {text, Bin}; text and byte strings are distinct."),
    "as_int/1": ("Extract a decoded CBOR integer.", "Accepts Erlang integers returned by the decoder.", "It does not coerce floats, strings, or binaries into integers."),
    "as_bool/1": ("Extract a decoded CBOR boolean.", "Accepts only true or false.", "It does not treat other values as truthy or falsey."),
    "ble_options/0": ("Return strict options for small BLE-oriented payloads.", "Provides conservative depth, item, byte, and string limits with floats, tags, and indefinite-length items disabled.", "It is not a Bluetooth transport implementation or a performance benchmark."),
}


def exports(source: str) -> list[str]:
    match = re.search(r"-export\(\[(.*?)\]\)\.", source, re.S)
    if not match:
        raise SystemExit("could not find -export block")
    return re.findall(r"([a-zA-Z0-9_]+/\d+)", match.group(1))


def specs(source: str, public: list[str]) -> dict[str, str]:
    found = {}
    remaining = list(public)
    pattern = r"-spec\s+([a-zA-Z0-9_]+)\((.*?)\)\s*->\s*(.*?)\."
    for match in re.finditer(pattern, source, re.S):
        name, args, ret = match.groups()
        key = next((item for item in remaining if item.startswith(name + "/")), None)
        if key is None:
            continue
        remaining.remove(key)
        args = re.sub(r"\s+", " ", args.strip())
        ret = re.sub(r"\s+", " ", ret.strip())
        found[key] = f"{name}({args}) -> {ret}"
    return found


def render(public: list[str], spec_map: dict[str, str]) -> str:
    out = [
        "# API Reference",
        "",
        "Generated from `src/avm_cbor.erl` by `scripts/gen-api-docs.py`.",
        "",
        "Do not edit this file by hand. Run:",
        "",
        "```bash",
        "python3 scripts/gen-api-docs.py",
        "```",
        "",
        "## Summary",
        "",
        "| Function | Purpose |",
        "|---|---|",
    ]
    for key in public:
        summary = DESCRIPTIONS.get(key, ("TODO document this function.", "", ""))[0]
        out.append(f"| `{key}` | {summary} |")

    out.extend(["", "## Functions"])
    for key in public:
        summary, what, what_not = DESCRIPTIONS.get(key, ("TODO document this function.", "TODO", "TODO"))
        out.extend([
            "",
            f"### `{key}`",
            "",
            summary,
            "",
            "**Spec**",
            "",
            "```erlang",
            spec_map.get(key, "TODO missing -spec"),
            "```",
            "",
            "**What it does**",
            "",
            what,
            "",
            "**What it is not**",
            "",
            what_not,
        ])
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if docs/api.md is not up to date")
    args = parser.parse_args()

    source = SRC.read_text(encoding="utf-8")
    public = exports(source)
    generated = render(public, specs(source, public))

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != generated:
            print("docs/api.md is not up to date. Run: python3 scripts/gen-api-docs.py", file=sys.stderr)
            return 1
        return 0

    OUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
